version: '3.9'
services:
  strapi:
    container_name: strapi_host
    image: strapi/strapi
    restart: unless-stopped
    volumes:
      - app_vol_sqlite:/srv/app
    environment:
      - DATABASE_FILENAME=/srv/app/data.db
    ports:
      - "${STRAPI_EXPOSED_PORT}:1337"

volumes:
  app_vol_sqlite:
