version: '3.9'
services:
  strapi:
    container_name: strapi_host
    image: strapi/strapi
    restart: unless-stopped
    volumes:
      - app_vol_post:/srv/app
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres_host
      - DATABASE_PORT=${STRAPI_DB_PORT}
      - DATABASE_NAME=${STRAPI_DB_NAME}
      - DATABASE_USERNAME=${STRAPI_DB_USER}
      - DATABASE_PASSWORD=${STRAPI_DB_PASSWORD}
    ports:
      - "${STRAPI_EXPOSED_PORT}:1337"
    depends_on:
      - db

  db:
    container_name: postgres_host
    image: postgres
    restart: unless-stopped
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${STRAPI_DB_USER}
      - POSTGRES_PASSWORD=${STRAPI_DB_PASSWORD}
      - POSTGRES_DB=${STRAPI_DB_NAME}
    ports:
      - "1$STRAPI_DB_PORT:$STRAPI_DB_PORT"

volumes:
  db_vol:
  app_vol_post:
